# -*- coding: utf-8 -*-
"""백준 5585.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Tn5wYBfmcIGY-Xsa8rw1F1PjgKHpGEs
"""

change = 1000-int(input())
count=0
coin =[500,100,50,10,5,1]

for i in range(len(coin)):
  count += (change//coin[i])
  change %= coin[i]

print(count)

