# -*- coding: utf-8 -*-
"""백준 11047.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Tn5wYBfmcIGY-Xsa8rw1F1PjgKHpGEs
"""

n, k = map(int, input().split())
number=[]
count=0
for i in range(n):
  a =int(input())
  number.append(a)

number.sort(reverse=True)
for i in range(len(number)):
  count += (k//number[i])
  k %= number[i]

print(count)

5200//4200

a =int(input())

