# -*- coding: utf-8 -*-
"""백준 11508.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Tn5wYBfmcIGY-Xsa8rw1F1PjgKHpGEs
"""

# 백준 11508
# 2+1 세일

N = int(input())

product=[]
result = 0

for i in range(N):
  sample=int(input())
  product.append(sample)

product.sort(reverse=True)
other= product[2::3]

result+=sum(product)-sum(other)
  
print(result)

