# -*- coding: utf-8 -*-
"""백준95.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgOS__IwigKoSQ9O6fNtrSdMtD37Tf9P
"""

import sys
input = sys.stdin.readline

s = list(input().rstrip())
bomb = list(input().rstrip())

stack = []

for i in range(len(s)):